stages:
  - build
  - deploy

build-job:
  stage: build
  only:
    - dev_server
  script:
    - docker build -t project-okapi-frontend:latest .

deploy-job:
  stage: deploy
  only:
    - dev_server
  script:
    - cd /opt/project-okapi/
    - docker compose up -d
