stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - docker build -t project-okapi-frontend:latest .

deploy-job:
  stage: deploy
  script:
    - cd /opt/project-okapi/
    - docker-compose down
    - docker-compose up -d